version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - dweb-network

  ipfs:
    image: ipfs/kubo:latest
    privileged: true
    ports:
      - "4001:4001"
      - "4001:4001/udp"
    volumes:
      - ./remove-lockfile.sh:/container-init.d/remove-lockfile.sh:ro
      - ipfs_data:/data/ipfs
      - ipfs_export:/export
    environment:
      - IPFS_PROFILE=server
    restart: always
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3

  file-server:
    build:
      context: ./dweb-be
      dockerfile: Dockerfile.filesrv
    ports:
      - "${FILE_SERVER_PORT:-5100}:5100"
    volumes:
      - sqlite-db:/usr/src/app/database
      - ./storage:/usr/src/app/storage
    env_file:
      - dweb-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - dweb-network

  deploy-service:
    build:
      context: ./dweb-be
      dockerfile: Dockerfile.deploysrv
    ports:
      - "${DEPLOY_SERVICE_PORT:-5200}:5200"
    volumes:
      - sqlite-db:/usr/src/app/database
    env_file:
      - dweb-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - dweb-network

  pinning-service:
    build:
      context: ./dweb-be
      dockerfile: Dockerfile.pinsrv
    ports:
      - "${PINNING_SERVICE_PORT:-5300}:5300"
    volumes:
      - sqlite-db:/usr/src/app/database
    env_file:
      - dweb-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - dweb-network

  frontend:
    build:
      context: ./dweb-fe
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      deploy-service:
        condition: service_started
      file-server:
        condition: service_started
      pinning-service:
        condition: service_started
    restart: always
    networks:
      - dweb-network

networks:
  dweb-network:

volumes:
  ipfs_data:
  ipfs_export:
  sqlite-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/sqlite-db
