version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dweb-network

  file-server:
    build:
      context: ./dweb-be
      dockerfile: Dockerfile.filesrv
    ports:
      - "${FILE_SERVER_PORT:-5100}:5100"
    volumes:
      - ./storage:/usr/src/app/storage
    env_file:
      - dweb-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - dweb-network

  deploy-service:
    build:
      context: ./dweb-be
      dockerfile: Dockerfile.deploysrv
    ports:
      - "${DEPLOY_SERVICE_PORT:-5200}:5200"
    env_file:
      - dweb-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - dweb-network

  frontend:
    build:
      context: ./dweb-fe
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      deploy-service:
        condition: service_started
      file-server:
        condition: service_started
    restart: always
    networks:
      - dweb-network

networks:
  dweb-network:
